# Generated by Django 3.0.6 on 2020-05-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
