# Generated by Django 3.0.6 on 2020-06-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderManager', '0002_auto_20200617_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=30),
        ),
    ]
