# Generated by Django 3.0.6 on 2020-05-16 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderManager', '0002_category_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isPayed',
            new_name='isPaid',
        ),
    ]
