# Generated by Django 3.0.6 on 2020-05-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderManager', '0003_auto_20200516_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
